# Notebook deployment workflow
name: dev Workflow
# Workflow trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'main'
jobs:
  databricks-dev:
    name: databricks dev
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      # Checkout the repository
      - name: Checkout
        uses: "actions/checkout@v4"
      # notebook deployment
      - name: Deploy Notebooks
        uses: microsoft/databricks-import-notebook@v1.0.0
        with:
          databricks-host: ${{ secrets.DATABRICKS_HOST }}
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          remote-path: /Workspace/Notebooks/databricks-cicd
          local-path: ${{ github.workspace }}/databricks-cicd
