# Notebook deployment workflow
name: dev Workflow
# Workflow trigger
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  db-notebook-deploy:
    name: databricks notebook deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      # Checkout the repository
      - name: Checkout
        uses: "actions/checkout@v4"
      # install databricks-cli
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0
      # notebook deployment
      - name: Deploy Notebooks
        uses: microsoft/databricks-import-notebook@v1.0.0
        with:
          databricks-host: ${{ secrets.DATABRICKS_HOST }}
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          remote-path: /Workspace/Notebooks
          local-path: ${{ github.workspace }}/notebook
